AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeWithMe project to send the article text to an SNS topic

Resources:
  SNSDispatcher:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.codewithme.awsnight.snsarticles.LambdaFunction
      Description: CodeWithMe project to send the article text to an SNS topic
      Runtime: java8
      MemorySize: 128
      Timeout: 25
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: cwm-articles
